*** Variables ***

${BASE_URL}                     https://training-platform2.doppio-tech.com/
${LOCAL_URL}                    http://192.8.8.124:8080/
${HEADLESS}                     false
${LOCALE_EN}                    en
${LOCALE_TH}                    th
${SHORT_TIMEOUT}                5s
${LONG_TIMEOUT}                 30s
${DEFAULT_HIGHLIGHT}            5s
${DEFAULT_RETRY_TIMES}          3x
${DEFAULT_RETRY_INTERVAL}       1000ms
${DELAY}                        0.0
${DEFAULT_COLOR}                Black
${REPLACE_TEXT}                 [replace_me]
