*** Variables ***

${auth_locator.input_email}         css=[data-testid="signin-email"]
${auth_locator.input_password}      css=[data-testid="signin-password"]
${auth_locator.cb_remember_me}      css=[data-testid="nav-search-input"]
${auth_locator.btn_sign_in}         css=[data-testid="signin-submit"]
${auth_locator.a_sign_up}           text=Create account

${auth_locator.signup.input_full_name}          css=[data-testid="signup-fullname"]
${auth_locator.signup.input_mobile_phone}       css=[data-testid="signup-phone"]
${auth_locator.signup.input_email}              css=[data-testid="signup-email"]
${auth_locator.signup.input_password}           css=[data-testid="signup-password"]
${auth_locator.signup.input_cf_password}        css=[data-testid="signup-confirm"]
${auth_locator.signup.btn_create_account}       css=[data-testid="signup-submit"]
${auth_locator.signup.btn_signin}               text=Sign in
